repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    args:
    - --select
    - I
    - --fix
    files: ^packages/
    types:
    - file
    - python
  - id: ruff-format
    files: ^packages/
    types:
    - file
    - python
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.4.18
  hooks:
  - id: pip-compile
    files: ^packages/crawler/pyproject.toml$
    args:
    - packages/crawler/pyproject.toml
    - --output-file
    - packages/crawler/requirements.txt
  - id: pip-compile
    files: ^packages/fuhnance/pyproject.toml$
    args:
    - packages/fuhnance/pyproject.toml
    - --output-file
    - packages/fuhnance/requirements.txt
