[project]
name = "crawler"
version = "0.1.0"
requires-python = ">=3.11"
description = "Contains all the code for crawling sites and watching for changes"
dependencies = [
  "boto3",
  "pandas",
  "matplotlib",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
