[project]
name = "crawler"
version = "0.1.0"
requires-python = ">=3.11"
description = "Contains all the code for crawling sites and watching for changes"
dependencies = [
  "dagster>=1.8.10",
  "dagster-cloud>=1.8.10",
  "common",
  "beautifulsoup4==4.12.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
common = { workspace = true }

[tool.uv]
dev-dependencies = []
