[project]
name = "fuhnance"
version = "0.1.0"
requires-python = ">=3.11"
description = "Contains all the code for crawling and calculating finance data"
dependencies = [
  "dagster>=1.8.10",
  "dagster-cloud>=1.8.10",
  "boto3",
  "pandas",
  "matplotlib",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
