[project]
name = "fuhnance"
version = "0.1.0"
description = "Contains all the code for crawling and calculating finance data"
dependencies = [
  "boto3",
  "pandas",
  "matplotlib",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"